#  List of 100 keywords commonly used by AI
ai_keywords = ["commendable", "innovative", "meticulous", "intricate", "notable", "versatile", "noteworthy", "invaluable", "pivotal", "potent", "fresh", "ingenious", "cogent", "ongoing", "tangible", "profound", "methodical", "laudable", "lucid", "appreciable", "fascinating", "adaptable", "admirable", "refreshing", "proficient", "intriguing", "thoughtful", "credible", "exceptional", "digestible", "prevalent", "interpretative", "remarkable", "seamless", "economical", "proactive", "interdisciplinary", "sustainable", "optimizable", "comprehensive", "vital", "pragmatic", "comprehensible", "unique", "fuller", "authentic", "foundational", "distinctive", "pertinent", "valuable", "invasive", "speedy", "inherent", "considerable", "holistic", "insightful", "operational", "substantial", "compelling", "technological", "beneficial", "excellent", "keen", "cultural", "unauthorized", "strategic", "expansive", "prospective", "vivid", "consequential", "manageable", "unprecedented", "inclusive", "asymmetrical", "cohesive", "replicable", "quicker", "defensive", "wider", "imaginative", "traditional", "competent", "contentious", "widespread", "environmental", "instrumental", "substantive", "creative", "academic", "sizeable", "extant", "demonstrable", "prudent", "practicable", "signatory", "continental", "unnoticed", "automotive", "minimalistic", "intelligent"]

text_path = "text.txt"

contains_ai_keywords = 0
matched_ai_keywords = []

with open(text_path, "r") as file:
    contents = file.read();
    contents = contents.split()

    for c in contents:
        for sus in ai_keywords:
            # If any keyword of the target text file matches any word of the 100 keywords commonly used by AI
            if c == sus:
                matched_ai_keywords.append(sus)
                contains_ai_keywords = contains_ai_keywords + 1

if contains_ai_keywords > 0:
    print(f"These texts could be generated by AI (E.g. ChatGPT)\nNumber of keywords matching AI generated words: {contains_ai_keywords}")
    print(f"matched_ai_keywords: {matched_ai_keywords}")

if contains_ai_keywords == 0:
    print(f"These texts seems to be original") 
# print(f"matched_ai_keywords: {matched_ai_keywords}")